<a href="https://colab.research.google.com/github/Tommy278710/Snip/blob/main/AI_ASSIGNMENT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SECTION 1
# **Libaries**
### 1. A libary is a set of already made code that helps in building and traning models faster rather than starting again. e.g matplotlib is used for plotting graphs/charts.so any time i want to use this libary i just need to import it as.. import matplotlib.pyplot as plt .rather than importing matplotlib every time i need to plot a graph.

### 2. we were imtroduced to Numpy and Pandas
#### Numpy stands for numerical python and is mostly used for working with numbers and arrays.

#### Pandas is used to load dataset csv files and helps to clean and organize data.

# SECTION 2

In [17]:
# NUMPY
import numpy as np
techcrush=np.array([32,4,66,86,32,12])
print (techcrush)# tommy

[32  4 66 86 32 12]

# SECTION 3

In [18]:
# step 1
import pandas as pd
# PANDAS
# creating student data
students ={
    "studentID":[101,102,103,104,105,106,107,108],
    "Name":["Tommyjr","Mr micheal","Aliya","Ayobami","Docars","Mide","Sariyat","Halima"],
    "Age":[23,18,24,26,19,20,21,25],
    "Department":["AI","AI","SLT","Networking","Civil engineer","Cyber security","LIS","CS"],
    "Scoer":[98,35,76,89,65,43,88,54],
    "Grade":["A","C","D","B","A","CD","BC","A"]
}
df = pd.DataFrame(students)
print(df)

   studentID        Name  Age      Department  Scoer Grade
0        101     Tommyjr   23              AI     98     A
1        102  Mr micheal   18              AI     35     C
2        103       Aliya   24             SLT     76     D
3        104     Ayobami   26      Networking     89     B
4        105      Docars   19  Civil engineer     65     A
5        106        Mide   20  Cyber security     43    CD
6        107     Sariyat   21             LIS     88    BC
7        108      Halima   25              CS     54     A

In [19]:

# step2
#HEADS
df.head(5)

   studentID        Name  Age      Department  Scoer Grade
0        101     Tommyjr   23              AI     98     A
1        102  Mr micheal   18              AI     35     C
2        103       Aliya   24             SLT     76     D
3        104     Ayobami   26      Networking     89     B
4        105      Docars   19  Civil engineer     65     A

In [7]:
#TAILS
df.tail(3)

   studentID     Name  Age      Department  Scoer Grade
5        106     Mide   20  Cyber security     43    CD
6        107  Sariyat   21             LIS     88    BC
7        108   Halima   25              CS     54     A

In [20]:
# step 3
print("shape:", df.shape) #(rows ,colums)

shape: (8, 6)


### print("shape:", df.shape) #(rows ,colums) this explain how many rows and colums are in the data

In [21]:
# step 4
df.info() # information about the data
df.describe() # basic indexs/statistics

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   studentID   8 non-null      int64
 1   Name        8 non-null      object
 2   Age         8 non-null      int64
 3   Department  8 non-null      object
 4   Scoer       8 non-null      int64
 5   Grade       8 non-null      object
dtypes: int64(3), object(3)
memory usage: 516.0+ bytes

       studentID      Age      Scoer
count    8.00000   8.0000   8.000000
mean   104.50000  22.0000  68.500000
std      2.44949   2.9277  23.058931
min    101.00000  18.0000  35.000000
25%    102.75000  19.7500  51.250000
50%    104.50000  22.0000  70.500000
75%    106.25000  24.2500  88.250000
max    108.00000  26.0000  98.000000

#### df.info() # information about the data
#### df.describe() # basic indexs/statistics . info gives the overview of the data/columns and basically all the information within the data. while describe gives statistical basics of the data

In [22]:
# step 5
print(df["Age"].unique())
print(df["Age"].nunique())

[23 18 24 26 19 20 21 25]
8

### Am really confused with numbers in datas .EDA structure ⚛